# Generated by Django 5.2.17 on 2026-09-06 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('target', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bạn', max_length=80)),
                ('gender', models.CharField(default='other', max_length=20)),
                ('age', models.PositiveIntegerField(default=25)),
                ('height', models.FloatField(default=170)),
                ('activity', models.CharField(default='moderate', max_length=30)),
                ('goal', models.CharField(default='maintain', max_length=30)),
                ('target_weight', models.FloatField(default=70)),
                ('start_weight', models.FloatField(default=77)),
                ('calories', models.PositiveIntegerField(default=2050)),
                ('protein', models.PositiveIntegerField(default=150)),
                ('carbs', models.PositiveIntegerField(default=220)),
                ('fat', models.PositiveIntegerField(default=65)),
                ('water', models.PositiveIntegerField(default=2500)),
                ('steps', models.PositiveIntegerField(default=10000)),
                ('frequency', models.PositiveIntegerField(default=4)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('onboarded', models.BooleanField(default=False)),
                ('score_weights', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
